config/routes.rb
Rails.application.routes.draw do
  devise_for :lawyers, controllers:{
    sessions: 'lawyers/sessions',
    registrations: 'lawyers/registrations'
  },
  path:"/",
  path_names:{registration: 'advogado',
              sign_up: '/cadastro'
  }
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    },
    path: "/",
    path_names: { sign_in: 'login',
                  sign_out: 'logout',
                  registration: 'usuario',
                  sign_up: '/cadastro' ,
                }
    devise_scope :user do
      authenticated :user do
    get '/perfil' => 'landing_page#perfil', as: :perfil
    get "perfil" => "landing_page#edit"
    put "avatar" => "landing_page#update"
    get 'advogado/match' => 'landing_page#match_lawyer'
      end
    end
  root to: 'landing_page#index'
  # root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lawyer.rb
class Lawyer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  validates_presence_of :first_name, :last_name, :state, :avatar
  validates :lawyer_id, presence: false
  has_many :users
  mount_uploader :avatar, AvatarUploader

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable

  belongs_to :lawyer
  validates_presence_of :first_name, :last_name, :state, :avatar
  validates :lawyer_id, presence: false
  mount_uploader :avatar, AvatarUploader


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout 'landingpage'
  # before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :get_lawyers
  #   protected
  
  #   def configure_permitted_parameters
  #     devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :state])
  #   end

  def get_user
    @user = current_user
  end
  def get_lawyers
    @lawyers = Lawyer.all
  end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
    layout 'landingpage'
    before_action :get_user,  only: [:perfil, :update, :match_lawyer]
    before_action :get_lawyers,  only: [:match_lawyer]

    def index
    end
    def perfil
    end

    def update
        puts('entrei')
        puts(@user)
        if @user.update_attributes(user_avatar_param)
            redirect_to perfil_path 
        else
            print('erro')
            render json: @user.errors 
        end
    end
    def match_lawyer
        if(@user.lawyer_id == nil)
            if(Lawyer.where(state: @user.state).count >= 1)
                lawyer_by_state = Lawyer.where(state: @user.state)
                @user.lawyer_id = lawyer_by_state.sample.id
                @user.save  
                redirect_to perfil_path
            else
                redirect_to perfil_path
                flash[:error] = 'No momento não há advogados do seu estado. Em breve, tente novamente!'
            end
        else
            redirect_to perfil_path
        end
    end
    def user_avatar_param
        params.require(:user).permit(:avatar)
    end
end

app/controllers/lawyers/registrations_controller.rb
class Lawyers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    @lawyer = Lawyer.new(sign_up_params)
    set_minimum_password_length
    print(@lawyer)
      if @lawyer.save
        redirect_to root_path
      else
        flash[:error] = 'Um erro ocorreu, não foi possível processar sua inscrição'
        render :new
      end
  end
  
  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  def sign_up_params
    params.require(:lawyer).permit(:avatar, :homologated, :first_name, :last_name, :state, :email, :password, :password_confirmation)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/lawyers/sessions_controller.rb
class Lawyer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    @user = User.new(sign_up_params)
    set_minimum_password_length
    if @user.save
      redirect_to new_user_session_path
    else
      flash[:error] = 'Um erro ocorreu, não foi possível processar sua inscrição' 
      render :new
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  def sign_up_params
    params.require(:user).permit(:avatar, :state, :first_name, :last_name, :email, :password, :password_confirmation)
  end
  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource_or_scope)
      perfil_path
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_message
        messages = ""
        [:notice, :info, :warning, :error].each {|type|
          if flash[type]
            messages += "#{flash[type]}"
          end
        }
        messages
      end
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/lawyers_helper.rb
module LawyersHelper
end

app/views/landing_page/_edit.html.erb
<%= form_for @user, url: { :action => "update" }, html: { id: "edit_avatar_user", method: :put } do |f| %>
<%= f.label :avatar, class: "label-file" do%>
<span>Selecionar</span>
<% end %>
<%= f.file_field :avatar, class:"form-control file-avatar"%>
<%= f.submit 'Atualizar', class:"btn btn-primary" %>
<% end %>

app/views/landing_page/index.html.erb
<header id="fh5co-header" class="fh5co-cover fh5co-cover-sm" role="banner" style="background-image:url(images/img_bg_2.jpg);">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center">
                <div class="display-t">
                    <div class="display-tc animate-box" data-animate-effect="fadeIn">
                        <h1>Precisa de um Advogado?</h1>
                        <h2>Encontre de forma rápida e prática um que mais se encaixe com as suas necessidades!</h2>
                        <%= link_to new_user_registration_path,  class: "cadastrar-causa" do %>
                            <span>CADASTRE-SE AGORA!</span>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>



<div id="fh5co-started">
    <div class="container">
        <div class="row animate-box">
            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                <h2>É advogado e quer entrar na plataforma?</h2>
                <p>Encontre mais clientes através da plataforma!</p>
                <span>*consulte regras*</span>
            </div>
        </div>
        <div class="row animate-box">
            <div class="col-md-8 col-md-offset-2 text-center">
                <%= link_to new_lawyer_registration_path,  class: "cadastrar-causa" do %>
                    <span>CLIQUE AQUI!</span>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/landing_page/perfil.html.erb
<div id="fh5co-services" class="main-form">
		<div class="container">
		<% if !flash_message.blank? %>
			<div class="alert alert-danger" role="alert" aria-label="Close">
				<%= flash_message %>
			</div>
		<% end %>
			<div class="row">
				<div class="col-md-3">
					<div class="fhco-cta-block">
						<div class="row avatar-row">
							<% if @user.avatar_url != nil %>
								<%= image_tag @user.avatar_url, class:'avatar'%>
							<% end %>
						</div>
						<div class="row">
							<%= render 'edit' %>
						</div>
					</div>
				</div>
				<div class="col-md-5">
					<div class="fhco-cta-block">
						<h2><strong>Olá,</strong> <%= @user.first_name %> <%= @user.last_name %> de <%= @user.state %> </h2>
						<h2><%= @user.email %></h2>
						<p>Dignissimos asperiores vitae velit veniam totam fuga molestias accusamus alias autem provident. Odit ab aliquam dolor eius.</p>
						<!-- <form action="#" id="fh5co-subscribe">
							<div class="form-group">
								<label for="email">Enter Email</label>
								<input type="text" class="form-control" id="email">
								<button class="btn btn-primary">Send</button>
							</div>
						</form> -->
					</div>
				</div>
				<div class="col-md-4">
                <% if @user.lawyer_id == nil %>
					<div class="fhco-cta-block">
						<h2>Encontre o advogado que mais se encaixa com você!</h2>
						<p>Dignissimos asperiores vitae velit veniam totam fuga molestias accusamus alias autem provident. Odit ab aliquam dolor eius.</p>
                        <p><%= link_to 'Clique aqui!', advogado_match_path, method: :get, class: "btn btn-primary"%>
                        </p>
					</div>
                <% end %>
                <% if @user.lawyer_id != nil %>
                <div class="fhco-cta-block">
					<div class="row avatar-flex-row">
						<span>Seu advogado: <h2> <%= @user.lawyer.first_name %> <%= @user.lawyer.last_name %> de <%= @user.lawyer.state %></h2> </span>
					</div>
					<div class="row avatar-flex-row">
						<% if @user.lawyer.avatar != nil %>
							<%= image_tag @user.lawyer.avatar, class:'avatar' %>
						<% end %>
					</div>
                    <h2><%= @user.lawyer.email %></h2>
                    
                    <p>Dignissimos asperiores vitae velit veniam totam fuga molestias accusamus alias autem provident. Odit ab aliquam dolor eius.</p>
                </div>
				<% end %>
				</div>
			</div>
		</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniAjudajus</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/layouts/landingpage.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
   <head>
      <title>Mini AJudaJus</title>
      <%= csrf_meta_tags %>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="language" content="pt-BR" />
      <link rel="icon" type="image/png" sizes="16x16" href="#">
      <meta name="author" content="Mini Ajuda Jus" />
      <meta name="description" content="Plataforma e Match com cliente x advogado" />
      <meta name="keywords" content="advogado cliente justica">
      <%= stylesheet_link_tag  'landingpage', media: 'all', 'data-turbolinks-track' => true %>
      <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,700,800" rel="stylesheet">
   </head>
   <body>
    <%= render "layouts/shared/shared" %>
    <%= javascript_include_tag 'landingpage' %>
   </body>
</html>

app/views/layouts/shared/_shared.html.erb
<div id="page">
<nav class="fh5co-nav" role="navigation">
<div class="top">
    <div class="container">
        <!-- <div class="row">
            <div class="col-xs-12 text-right">
                <ul class="fh5co-social">
                    <li><a href="#"><i class="icon-facebook"></i></a></li>
                    <li><a href="#"><i class="icon-instagram"></i></a></li>
                </ul>
            </div>
        </div> -->
    </div>
</div>
<div class="top-menu">
    <div class="container">
        <div class="row">
            <div class="col-xs-2">
                <div id="fh5co-logo"><%= link_to 'M.AjudaJus', root_path %><span>.</span></div>
            </div>
            <div class="col-xs-10 text-right menu-1">
                <ul>
                    <li><%=link_to 'Início', root_path%></li>
                    <% if user_signed_in? %>
                         <li class="has-dropdown">
                            <%= link_to 'Minha conta ↓ ', class: "link-top" %>
                            <ul class="dropdown">
                                <li><%= link_to 'Perfil', perfil_path %></li>
                                <!-- <li><a href="#">eCommerce</a></li>
                                <li><a href="#">Branding</a></li> -->
                                <li><%= link_to(destroy_user_session_path, :method => :get)  do %>
                                    Sair
                                <% end %></li>
                            </ul>
                        </li>
                        <% else %>
                        <li  class="btn-cta">
                            <%=link_to new_user_session_path do %>
                            <span>Login</span>
                        <% end %>
                    <% end %>
                </ul>
            </div>
        </div>
        
    </div>
</div>
</nav>
<%= yield %>
<footer id="fh5co-footer" role="contentinfo">
        <div class="container">
            <div class="row copyright">
                <div class="col-md-12 text-center">
                    <p class="custom-footer">
                        <small class="block">&copy; 2016 Free HTML5. All Rights Reserved.</small> 
                        <small class="block"> Customized by Rayane Santos</small> 
                    </p>
                </div>
            </div>
        </div>
    </footer>
    
    <div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
    </div>
</div>